### ISSUE TITLE
Position and size of some elements differ from the specs 

### ISSUE THREAD

**Issue by michmuel** [openoereb/pyramid_oereb_mfp#102] opened 2022-03-25 10:55 UTC
Some elements are larger/smaller or at another position than in the specs. See comments in the PDFs.

PDFs

[CH107812348389_comments.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/8349748/CH107812348389_comments.pdf)
[CH871277778361_comments.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/8349735/CH871277778361_comments.pdf)

Specs

https://www.cadastre.ch/content/cadastre-internet/de/manual-oereb/service/extract/static/_jcr_content/contentPar/tabs_copy_copy_copy_/items/dokumente/tabPar/downloadlist/downloadItems/426_1475413822017.download/Weisung-statischer-Auszug-de.pdf

**Comment by marionb** [comment] 2022-04-28 06:50
@michmuel can you specify which of the elements of this issue still need to be looked at after the fix of PR #107?

**Comment by michmuel** [comment] 2022-04-28 08:06
@marionb

CH107812348389_comments.pdf
page 1: Background map --> We solved this issue as it is a matter of our configuration.
page 4: Spacing issue remains.

CH871277778361_comments.pdf
page 1: Background map and area label issues solved. 
page 1: The other issues remain open. Scale label definition possibly inconsistent in specs.
page 2: Texts are ok (https://github.com/openoereb/pyramid_oereb_mfp/issues/97).
page 3: Issue remain.
page 4: Positioning issues: The position of the respective elements are different now. But they do not agree with the specs. Why were the positions changed in this way? @voisardf do you know something about it?
page 4: The "dash" issue remains. Its probably more an aesthetic thing than an instruction from specs. The use of a dash or better no dash should be consistent in the document.
page 10: The issue regarding the page break remains.

**Comment by marionb** [comment] 2022-04-28 10:21
@michmuel 
It is quite hard to discuss any of these points as it requires to open about three files and it is all in one issue. 
If you can take this apart more and perhaps use screen shots instead of annotated PDF it would help to make the discussion easier and we know we are talking about the same things. I am not sure if some of the annotations move when I opened them on my system. 
Are these PDFS already with the new version of the templates? 

I have some questions here:

1. CH107812348389_comments.pdf

> CH107812348389_comments.pdf: page 4: Spacing issue remains.

![image](https://user-images.githubusercontent.com/1460598/165727172-dcecaaba-2919-4409-9224-7a2df1bf3bfd.png)

I am not sure if I am on the wrong page here but I do not see a spec that about "40mm vertical spacing".
the spec shows this:
![image](https://user-images.githubusercontent.com/1460598/165727578-d40ad4d7-7d6a-44f5-bc7b-a661e0d10182.png)

3. CH871277778361_comments.pdf
> page 1: The other issues remain open. Scale label definition possibly inconsistent in specs.

what do you mean with possibly? Can you be more specific please.

4. CH871277778361_comments.pdf

> page 3: Issue remain.

See my comment in issue #98

5. CH871277778361_comments.pdf

> page 4: The "dash" issue remains. Its probably more an aesthetic thing than an instruction from specs. The use of a dash or better no dash should be consistent in the document.

note this is a duplicate of issue #99

**Comment by michmuel** [comment] 2022-04-29 07:12
@marionb I agree that this issue is not optimally presented for fixing the respective code.

1.
![Screenshot from 2022-04-29 08-18-34](https://user-images.githubusercontent.com/77100084/165893907-a6fe5636-d30c-40af-98d7-43aa6d78cadf.png)

3.
page 12 of the specs:
"Das angezeigte Massstabsymbol ist zu verwenden mit auf 5er- resp. 10er-Werte gerundeten Ein­heiten. Das Symbol ist mit einem weissen Halo zu umgeben."
![Screenshot from 2022-04-29 08-22-37](https://user-images.githubusercontent.com/77100084/165894204-29b274f5-49ca-45af-9edb-53c2b3025c46.png)

But:
page 1 of appendix A
![Screenshot from 2022-04-29 08-23-56](https://user-images.githubusercontent.com/77100084/165894357-58c0253d-8aa0-47c7-9bf5-0511e2fc005e.png)

==> The used symbol is the same as shown in page 12. That is ok. The implemented rounding is appropriate as for small properties rounding to units of 5 or 10 makes no sense. However, the size of the symbol should be fixed.

**Comment by marionb** [comment] 2022-04-29 19:57
@michmuel

- The scale issue looks like an issue in MFP. Setting the width is not fully respected. Should I investigate more on this?
- > Positioning issues: The position of the respective elements are different now. But they do not agree with the specs. Why were the positions changed in this way? @voisardf do you know something about it?

    I think this should be about what is in the specs but it is hard to set this 100% the same.

**Comment by marionb** [comment] 2022-05-02 09:24
@voisardf I'll assign this also to you so so you are also informed.
For the moment I left the problem with the scale I think this will require more time.

**Comment by michmuel** [comment] 2022-05-02 09:42
@marionb Seems fine to me. Thanks. I suggest closing this issue and continuing working on scale and the minor deviations from specs only if really required.

**Comment by marionb** [comment] 2022-05-02 12:12
OK thanks @michmuel then I'll merge and close this issue. You can open a new one for he scale if it is needed.

**Closed as completed** 2022-05-02 12:14 UTC
