### ISSUE TITLE
legal base label not printed when page break occurs

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb_mfp#36] opened 2019-10-23 15:40 UTC
In some cases, when a page break occurs in the legal bases band, the label is not printed (page 3):

[20191023011222_extract.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/3763225/20191023011222_extract.pdf)

**Comment by jwkaltz** [comment] 2019-11-04 10:47
@voisardf in addition, the line separation for "Informations et renvois supplémentaires" seems to disappear in this case. 
I received an information from Geoinfo that in some cases, the content of "Weitere Information and Hinweise" and "Zuständige Stelle" can get mixed: see https://oereb.ai.ch/ktai/wsgi/oereb/extract/reduced/pdf/CH914185597709 on page 9/10. 
I wonder if this has the same cause as what you are describing.

**Comment by voisardf** [comment] 2019-11-20 08:07
@jwkaltz: I could not reproduce this problem here (see attached pdf)? Is the issue still hanging in AI?
 
[20191120085717_extract.pdf](https://github.com/openoereb/pyramid_oereb_mfp/files/3868004/20191120085717_extract.pdf)

**Comment by MaxHoeferGEOINFO** [comment] 2019-11-20 09:56
Hi - we changed something in the data, that's why that example does not work anymore. I will look for a new example. 

In the meantime I have found this: https://oereb.ai.ch/ktai/wsgi/oereb/extract/reduced/pdf/CH880959417746
Look at page 5 & 6 - does that issue belong in this item too? 

Thanks
Max

**Comment by MaxHoeferGEOINFO** [comment] 2019-11-21 13:14
Hello everyone

I actually did not find a current example for that issue. All I have is a screenshot of the issue, which we had for one geometry in the past. The example does not work anymore, because the legal documents changed, so the space needed changed too. 
Please find the example attached. 
I assume this will not help a lot, will it?
![Zust Stelle](https://user-images.githubusercontent.com/54711581/69341065-1e705880-0c69-11ea-98e5-f77ae14f3f78.png)

I can only reproduce the issue mentioned in my previous post. 
Thanks & Regards
Max

**Comment by jwkaltz** [comment] 2019-12-16 12:09
@voisardf Baselstadt (@svareg ) has now also mentioned this kind of problem, and looking at current dummy data report, I can also see it:
![Screenshot from 2019-12-16 13-04-57](https://user-images.githubusercontent.com/9261252/70905666-be20cc80-2004-11ea-9ac3-c3bcf1c7f260.png)
The problem does not always look the same - sometimes a header is missing, sometimes a separation line, sometimes both, like in this example where the label "Weitere Informationen und Hinweise" is missing. All problem reports do have one thing in common: this happens only when the content is longer than 1 page.

This issue is currently marked as "usergroup work". Is it still the case that you / the user group plan to work on it?

**Comment by voisardf** [comment] 2019-12-16 13:22
@jwkaltz: I will try to fix this issues this week. Otherwise I will let you know.

**Comment by voisardf** [comment] 2019-12-20 10:46
@jwkaltz: I'm sorry, I will finally not be able to fix the issues this year. So if you have the ressources at c2c to do so, go ahead.

**Closed as completed** 2019-12-23 08:15 UTC
Labels: bug, enhancement, usergroup work
